stages:
  - deploy

thingideploy:
  stage: deploy
  image: "python:3.9.6-buster"
  script:
    - git clone https://gitlab.com/chrismettal/thingideploy.git
    - cd thingideploy
    - pip install -r requirements.txt
    - python3 ./thingideploy.py --deploy-project="$API_KEY" --path="$CI_PROJECT_DIR"/3d_printing/DIN_rail_case/
    artifacts:
      paths:
        - CreationResponse.json
        - PatchResponse.json
        - ThingURL.txt
        - ThingID.txt
      expire_in: 1 week
  only:
    changes:
      - 3d_printing/DIN_rail_case/**/*
      - 3d_printing/DIN_rail_case/*