stages:
  - deploy

Thingideploy:
  stage: deploy
  image: "python:3.9.6-alpine3.14"
  script:
    - git clone https://gitlab.com/chrismettal/thingideploy
    - cd thingideploy
    - pip install -r requirements.txt
    - cd ..
    - ./thingideploy/thingideploy.py "$CI_PROJECT_DIR" --deploy-project="$API_KEY"
  when: manual