stages:
  - deploy

deploy_thingiverse:
  stage: deploy
  image: "python:3.9.6-buster"
  script:
    - pip install threedeploy --upgrade
    - threedeploy --deploy-project-thingiverse="$API_KEY" --path="$CI_PROJECT_DIR"/3d_printing/DIN_rail_case/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/3d_printing/DIN_rail_case/CreationResponse.json
      - $CI_PROJECT_DIR/3d_printing/DIN_rail_case/PatchResponse.json
      - $CI_PROJECT_DIR/3d_printing/DIN_rail_case/ThingURL.txt
      - $CI_PROJECT_DIR/3d_printing/DIN_rail_case/ThingID.txt
    expire_in: 1 week
  only:
    changes:
      - 3d_printing/DIN_rail_case/**/*
      - 3d_printing/DIN_rail_case/*