stages:
  - deploy

Thingideploy:
  stage: deploy
  image: "python:3.9.6-buster"
  script:
    - git clone https://gitlab.com/chrismettal/thingideploy
    - python -m venv .venv
    - source .venv/bin/activate
    - cd thingideploy
    - pip install -r requirements.txt
    - ./thingideploy.py "$CI_PROJECT_DIR"/3d_printing/DIN_rail_case/ --deploy-project="$API_KEY"
  when: manual