M48
; DRILL file {KiCad (5.99.0-11096-g937f5138db)} date Mon Jul  5 20:04:56 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-07-05T20:04:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11096-g937f5138db)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X136.86Y-127.99
X160.16Y-72.0
T0
M30
